version: '3'
services:
  web:
    image: ghcr.io/fsr5-fhaachen/strichlistensystem:latest
    container_name: strichlistensystem-web
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb
    environment:
      APP_NAME: '${APP_NAME}'
      APP_ENV: '${APP_ENV}' # set to local if you want to test without https
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG}'
      APP_URL: '${APP_URL}'
      APP_VPN_IP: '${APP_VPN_IP}'
      CSV_EXPORT_PW: '${CSV_EXPORT_PW}'
      #TELEGRAM_BOT_TOKEN: '${TELEGRAM_BOT_TOKEN}'
      #TELEGRAM_BOT_INFO_CHANNEL_ID: '${TELEGRAM_BOT_INFO_CHANNEL_ID}'
      #TELEGRAM_BOT_WARNING_CHANNEL_ID: '${TELEGRAM_BOT_WARNING_CHANNEL_ID}'
      OCTANE_HTTPS: '${OCTANE_HTTPS}' # set to false if you want to test without https
      OCTANE_WORKERS: '${OCTANE_WORKERS}'
      OCTANE_MAX_REQUESTS: '${OCTANE_MAX_REQUESTS}'
      LOG_CHANNEL: '${LOG_CHANNEL}'
      LOG_LEVEL: '${LOG_LEVEL}'
      DB_CONNECTION: '${DB_CONNECTION}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      BROADCAST_DRIVER: '${BROADCAST_DRIVER}'
      CACHE_DRIVER: '${CACHE_DRIVER}'
      FILESYSTEM_DRIVER: '${FILESYSTEM_DRIVER}'
      QUEUE_CONNECTION: '${QUEUE_CONNECTION}'
      SESSION_DRIVER: '${SESSION_DRIVER}'
      SESSION_LIFETIME: '${SESSION_LIFETIME}'
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      REDIS_PORT: '${REDIS_PORT}'
    volumes:
      - /opt/strichlistensystem/images:/var/www/html/resources/img_import
      - /opt/strichlistensystem/imported_images:/var/www/html/public/images
    ports:
      - "8000:8000"
    networks:
      - strichlistensystem
  redis:
    image: redis
    container_name: strichlistensystem-redis
    restart: unless-stopped
    command: redis-server --requirepass '${REDIS_PASSWORD}'
#    ports:
#      - "6379:6379"
    networks:
      - strichlistensystem
  mariadb:
    image: mariadb
    container_name: strichlistensystem-mariadb
    restart: unless-stopped
#    ports:
#      - "3306:3306"
    environment:
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_ROOT_PASSWORD: USE_SECRET_STRING_HERE
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - strichlistensystem_mariadb:/var/lib/mysql/
    networks:
      - strichlistensystem
  wireguard:
    image: linuxserver/wireguard
    container_name: strichlistensystem-wireguard
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      SERVERURL: vpn.gerolstein.fsr5.de
      LOG_CONFS: true
    volumes:
      - /opt/strichlistensystem/wireguard/:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - "NET_ADMIN"
      - "SYS_MODULE"
networks:
  strichlistensystem:
volumes:
  strichlistensystem_mariadb: