version: '3'
services:
  web:
    image: ghcr.io/fsr5-fhaachen/strichlistensystem:latest
    container_name: strichlistensystem-web
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb
    environment:
      APP_NAME: '${APP_NAME}'
      APP_ENV: '${APP_ENV}' # set to local if you want to test without https
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG}'
      APP_URL: '${APP_URL}'
      APP_VPN_IP: '${APP_VPN_IP}'
      CSV_EXPORT_PW: '${CSV_EXPORT_PW}'
      #TELEGRAM_BOT_TOKEN: '${TELEGRAM_BOT_TOKEN}'
      #TELEGRAM_BOT_INFO_CHANNEL_ID: '${TELEGRAM_BOT_INFO_CHANNEL_ID}'
      #TELEGRAM_BOT_WARNING_CHANNEL_ID: '${TELEGRAM_BOT_WARNING_CHANNEL_ID}'
      OCTANE_HTTPS: '${OCTANE_HTTPS}' # set to false if you want to test without https
      OCTANE_WORKERS: 1
      OCTANE_MAX_REQUESTS: '${OCTANE_MAX_REQUESTS}'
      LOG_CHANNEL: '${LOG_CHANNEL}'
      LOG_LEVEL: '${LOG_LEVEL}'
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: strichlistensystem
      DB_USERNAME: strichlistensystem
      DB_PASSWORD: password
      BROADCAST_CONNECTION: '${BROADCAST_CONNECTION}'
      CACHE_STORE: '${CACHE_STORE}'
      FILESYSTEM_DRIVER: '${FILESYSTEM_DRIVER}'
      QUEUE_CONNECTION: '${QUEUE_CONNECTION}'
      SESSION_DRIVER: '${SESSION_DRIVER}'
      SESSION_LIFETIME: '${SESSION_LIFETIME}'
      REDIS_HOST: redis
      REDIS_PASSWORD: password
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    networks:
      - strichlistensystem
  redis:
    image: redis
    container_name: strichlistensystem-redis
    restart: unless-stopped
    command: redis-server --requirepass password
#    ports:
#      - "6379:6379"
    networks:
      - strichlistensystem
  mariadb:
    image: mariadb
    container_name: strichlistensystem-mariadb
    restart: unless-stopped
#    ports:
#      - "3306:3306"
    environment:
      MARIADB_DATABASE: strichlistensystem
      MARIADB_ROOT_PASSWORD: secret-root-password
      MARIADB_USER: strichlistensystem
      MARIADB_PASSWORD: password
    volumes:
      - strichlistensystem_mariadb:/var/lib/mysql/
    networks:
      - strichlistensystem
networks:
  strichlistensystem:
volumes:
  strichlistensystem_mariadb:
